site_name: TigerGraph CuGraph Integration
site_url: https://github.com/dmccrearytg/tg-cugraph
site_description: 'This website is for setting up demos for teaching the TigerGraph CuGraph course.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccrearytg.github.io/tg-cugraph'
repo_url: 'https://github.com/dmccrearytg/tg-cugraph'
edit_uri: edit/master/docs/

nav:
  - Home: index.md
  - About: about.md
  - Concepts:
    - Introduction: concepts/index.md
    - Architecture: concepts/architecture.md
  - Glossary: glossary.md
  - References: references.md
  - Contact: contact.md

# edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/tg-logo-small.png
  favicon: img/favicon.ico
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
  # you must have the mkdocs material images and the cairo libraries installed: https://t.ly/MfX6u
  # I had to add the following to my .zshrc file
  # export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
  #  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
# extra:
#  analytics:
#    provider: google
#    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-BBR7MPK96Z